server:
  port: 8383
  address: 127.0.0.1
  sessionTimeout: 30
  contextPath: /



nodes-wallets-definition:
  nb-trx-thread: 10
  time-before-resync-trx-id: 2000
  nb-trx-resync-trx-id: 500
  increment-factor: 13
  nodes:
    - address: 10.0.0.1
      port: 9090
      from-public-key: 
      from-private-key: 
      to-public-key: 
      time-trx-wait-ms: 0
    - address: 10.0.0.1
      port: 9090
      from-public-key: 
      from-private-key: 
      to-public-key: 
      time-trx-wait-ms: 0
    - address: 10.0.0.2
      port: 9090
      from-public-key: 
      from-private-key: 
      to-public-key: 
      time-trx-wait-ms: 0

debug: false
trace: false
logging.file: logs/test-credits.log




